version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: homeorholiday-postgres
    restart: always
    environment:
      POSTGRES_USER: HomeOrHoliday
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: HomeOrHoliday
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: homeorholiday-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/HomeOrHoliday
      - SPRING_DATASOURCE_USERNAME=HomeOrHoliday
      - SPRING_DATASOURCE_PASSWORD=123456
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge