version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: homeorholiday-postgres
    restart: always
    environment:
      POSTGRES_USER: HomeOrHoliday
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: HomeOrHoliday
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: