spring:
  application:
    name: HomeOrHolidayBackend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  graphql:
    graphiql:
      enabled: true
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}
      roles:
        ADMIN

app:
  jwt:
    secret: ${JWT_SECRET}
    # Access token default expiration: 24 hours (in milliseconds)
    expiration: ${JWT_EXPIRATION:86400000}
    # Refresh token default expiration: 7 days (in milliseconds)
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}